language: node_js
node_js:
  - 6
sudo: required
services:
  - docker
stages:
  - lint
  - build
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: lint
      script:
        - npm i
        - npm run lint
    - script:
        - cd server
        - npm i
        - npm run lint
    - stage: build
      script:
    - script:
        - cd server
        - docker build -t icmusictech/server .
    - stage: deploy
      script:
        - docker login -u "$DOCKER_HUB_LOGIN" -p "$DOCKER_HUB_PASSWORD"
        - docker build -t icmusictech/website .
        - docker push icmusictech/website
    - script:
        - cd server
        - docker login -u "$DOCKER_HUB_LOGIN" -p "$DOCKER_HUB_PASSWORD"
        - docker build -t icmusictech/server .
        - docker push icmusictech/server
