version: '3'
services:
  website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./src:/musictech/src"
      - "./public:/musictech/public"
  database:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musictech
