version: '3'
services:
  website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./src:/musictech/src"
      - "./public:/musictech/public"
  database:
    image: dwmkerr/dynamodb
    ports:
      - "8000:8000"
    command: ["-sharedDb"]
